DROP TABLE IF EXISTS ref_supplier_country
;
CREATE TABLE ref_supplier_country
    AS
SELECT * FROM (VALUES
    ('AE', 'AR', 'AED', '+971', 'Other', 'United Arab Emirates'),
    ('AL', 'SQ', 'ALL', '+355', 'Other', 'Albania'),
    ('AT', 'DE', 'EUR', '+43',  'VAT',   'Austria'),
    ('AU', 'EN', 'AUD', '+61',  'Other', 'Australia'),
    ('BA', 'BS', 'BAM', '+387', 'Other', 'Bosnia and Herzegovina'),
    ('BE', 'NL', 'EUR', '+32',  'VAT',   'Belgium'),
    ('BG', 'BG', 'BGN', '+359', 'Other', 'Bulgaria'),
    ('BM', 'EN', 'BMD', '+1',   'Other', 'Bermuda'),
    ('BR', 'PT', 'BRL', '+55',  'Other', 'Brazil'),
    ('CA', 'EN', 'CAD', '+1',   'Other', 'Canada'),
    ('CH', 'DE', 'CHF', '+41',  'Other', 'Switzerland'),
    ('CI', 'FR', 'XOF', '+225', 'Other', 'Ivory Coast'),
    ('CL', 'ES', 'CLP', '+56',  'Other', 'Chile'),
    ('CM', 'FR', 'XAF', '+237', 'Other', 'Cameroon'),
    ('CN', 'ZH', 'CNY', '+86',  'Other', 'China'),
    ('CR', 'ES', 'CRC', '+506', 'Other', 'Costa Rica'),
    ('CZ', 'CS', 'CZK', '+420', 'Other', 'Czech Republic'),
    ('DE', 'DE', 'EUR', '+49',  'VAT',   'Germany'),
    ('DK', 'DA', 'DKK', '+45',  'VAT',   'Denmark'),
    ('DZ', 'AR', 'DZD', '+213', 'Other', 'Algeria'),
    ('EC', 'ES', 'USD', '+593', 'Other', 'Ecuador'),
    ('EE', 'ET', 'EUR', '+372', 'Other', 'Estonia'),
    ('ES', 'ES', 'EUR', '+34',  'VAT',   'Spain'),
    ('FI', 'FI', 'EUR', '+358', 'VAT',   'Finland'),
    ('FR', 'FR', 'EUR', '+33',  'VAT',   'France'),
    ('GB', 'EN', 'GBP', '+44',  'VAT_UK', 'United Kingdom'),
    ('GR', 'EL', 'EUR', '+30',  'Other', 'Greece'),
    ('HK', 'ZH', 'HKD', '+852', 'Other', 'Hong Kong'),
    ('HR', 'HR', 'EUR', '+385', 'Other', 'Croatia'),
    ('HU', 'HU', 'HUF', '+36',  'Other', 'Hungary'),
    ('IE', 'EN', 'EUR', '+353', 'VAT_IE', 'Ireland'),
    ('IL', 'HE', 'ILS', '+972', 'Other', 'Israel'),
    ('IM', 'EN', 'GBP', '+44',  'Other', 'Isle of Man'),
    ('IN', 'HI', 'INR', '+91',  'Other', 'India'),
    ('IS', 'IS', 'ISK', '+354', 'Other', 'Iceland'),
    ('IT', 'IT', 'EUR', '+39',  'VAT',   'Italy'),
    ('JE', 'EN', 'GBP', '+44',  'Other', 'Jersey'),
    ('JP', 'JA', 'JPY', '+81',  'Other', 'Japan'),
    ('KR', 'KO', 'KRW', '+82',  'Other', 'South Korea'),
    ('LV', 'LV', 'EUR', '+371', 'Other', 'Latvia'),
    ('MA', 'AR', 'MAD', '+212', 'Other', 'Morocco'),
    ('MC', 'FR', 'EUR', '+377', 'Other', 'Monaco'),
    ('MK', 'MK', 'MKD', '+389', 'Other', 'North Macedonia'),
    ('MX', 'ES', 'MXN', '+52',  'Other', 'Mexico'),
    ('NG', 'EN', 'NGN', '+234', 'Other', 'Nigeria'),
    ('NL', 'NL', 'EUR', '+31',  'VAT',   'Netherlands'),
    ('NO', 'NO', 'NOK', '+47',  'Other', 'Norway'),
    ('NZ', 'EN', 'NZD', '+64',  'Other', 'New Zealand'),
    ('PL', 'PL', 'PLN', '+48',  'Other', 'Poland'),
    ('PT', 'PT', 'EUR', '+351', 'VAT',   'Portugal'),
    ('PY', 'ES', 'PYG', '+595', 'Other', 'Paraguay'),
    ('RO', 'RO', 'RON', '+40',  'Other', 'Romania'),
    ('RS', 'SR', 'RSD', '+381', 'Other', 'Serbia'),
    ('SE', 'SV', 'SEK', '+46',  'VAT',   'Sweden'),
    ('SG', 'EN', 'SGD', '+65',  'Other', 'Singapore'),
    ('SK', 'SK', 'EUR', '+421', 'Other', 'Slovakia'),
    ('SN', 'FR', 'XOF', '+221', 'Other', 'Senegal'),
    ('TT', 'EN', 'TTD', '+1',   'Other', 'Trinidad and Tobago'),
    ('US', 'EN', 'USD', '+1',   'EIN',   'United States'),
    ('ZA', 'EN', 'ZAR', '+27',  'Other', 'South Africa'),
    -- Additional countries from source data
    ('CY', 'EL', 'EUR', '+357', 'Other', 'Cyprus'),
    ('DO', 'ES', 'DOP', '+1',   'Other', 'Dominican Republic'),
    ('GE', 'KA', 'GEL', '+995', 'Other', 'Georgia'),
    ('ID', 'ID', 'IDR', '+62',  'Other', 'Indonesia'),
    ('JM', 'EN', 'JMD', '+1',   'Other', 'Jamaica'),
    ('KY', 'EN', 'KYD', '+1',   'Other', 'Cayman Islands'),
    ('KZ', 'KK', 'KZT', '+7',   'Other', 'Kazakhstan'),
    ('LS', 'EN', 'LSL', '+266', 'Other', 'Lesotho'),
    ('LT', 'LT', 'EUR', '+370', 'Other', 'Lithuania'),
    ('MT', 'MT', 'EUR', '+356', 'VAT',   'Malta'),
    ('MY', 'MS', 'MYR', '+60',  'Other', 'Malaysia'),
    ('PH', 'TL', 'PHP', '+63',  'Other', 'Philippines'),
    ('QA', 'AR', 'QAR', '+974', 'Other', 'Qatar'),
    ('SA', 'AR', 'SAR', '+966', 'Other', 'Saudi Arabia'),
    ('SI', 'SL', 'EUR', '+386', 'Other', 'Slovenia'),
    ('TH', 'TH', 'THB', '+66',  'Other', 'Thailand'),
    ('TR', 'TR', 'TRY', '+90',  'Other', 'Turkey'),
    ('UA', 'UK', 'UAH', '+380', 'Other', 'Ukraine'),
    ('UY', 'ES', 'UYU', '+598', 'Other', 'Uruguay')
) AS t(country_code, language_code, currency_code, phone_code, tax_id_type, country_name)
;
