DROP TABLE IF EXISTS ref_country_county_state_town_mapping
;
CREATE TABLE ref_country_county_state_town_mapping
    AS
SELECT
       *
  FROM (VALUES
          ('GB', 'London', 'Greater London')
        , ('GB', 'Birmingham', 'West Midlands')
        , ('GB', 'Manchester', 'Greater Manchester')
        , ('GB', 'Leeds', 'West Yorkshire')
        , ('GB', 'Liverpool', 'Merseyside')
        , ('GB', 'Sheffield', 'South Yorkshire')
        , ('GB', 'Newcastle upon Tyne', 'Tyne and Wear')
        , ('GB', 'Gateshead', 'Tyne and Wear')
        , ('GB', 'Sunderland', 'Tyne and Wear')
        , ('GB', 'Bradford', 'West Yorkshire')
        , ('GB', 'Huddersfield', 'West Yorkshire')
        , ('GB', 'Wakefield', 'West Yorkshire')
        , ('GB', 'Nottingham', 'Nottinghamshire')
        , ('GB', 'Derby', 'Derbyshire')
        , ('GB', 'Leicester', 'Leicestershire')
        , ('GB', 'Coventry', 'West Midlands')
        , ('GB', 'Wolverhampton', 'West Midlands')
        , ('GB', 'Stoke-on-Trent', 'Staffordshire')
        , ('GB', 'Walsall', 'West Midlands')
        , ('GB', 'Solihull', 'West Midlands')
        , ('GB', 'Northampton', 'Northamptonshire')
        , ('GB', 'Milton Keynes', 'Buckinghamshire')
        , ('GB', 'Reading', 'Berkshire')
        , ('GB', 'Slough', 'Berkshire')
        , ('GB', 'Maidenhead', 'Berkshire')
        , ('GB', 'Wokingham', 'Berkshire')
        , ('GB', 'Bristol', 'Bristol')
        , ('GB', 'Bath', 'Somerset')
        , ('GB', 'Exeter', 'Devon')
        , ('GB', 'Plymouth', 'Devon')
        , ('GB', 'Torquay', 'Devon')
        , ('GB', 'Portsmouth', 'Hampshire')
        , ('GB', 'Southampton', 'Hampshire')
        , ('GB', 'Winchester', 'Hampshire')
        , ('GB', 'Brighton', 'East Sussex')
        , ('GB', 'Hove', 'East Sussex')
        , ('GB', 'Worthing', 'West Sussex')
        , ('GB', 'Chichester', 'West Sussex')
        , ('GB', 'Canterbury', 'Kent')
        , ('GB', 'Maidstone', 'Kent')
        , ('GB', 'Dover', 'Kent')
        , ('GB', 'Ashford', 'Kent')
        , ('GB', 'Cambridge', 'Cambridgeshire')
        , ('GB', 'Peterborough', 'Cambridgeshire')
        , ('GB', 'Norwich', 'Norfolk')
        , ('GB', 'Ipswich', 'Suffolk')
        , ('GB', 'Colchester', 'Essex')
        , ('GB', 'Chelmsford', 'Essex')
        , ('GB', 'Basildon', 'Essex')
        , ('GB', 'Oxford', 'Oxfordshire')
        , ('GB', 'Swindon', 'Wiltshire')
        , ('GB', 'Salisbury', 'Wiltshire')
        , ('GB', 'Gloucester', 'Gloucestershire')
        , ('GB', 'Cheltenham', 'Gloucestershire')
        , ('GB', 'Cardiff', 'Glamorgan')
        , ('GB', 'Swansea', 'Glamorgan')
        , ('GB', 'Newport', 'Monmouthshire')
        , ('GB', 'Edinburgh', 'City of Edinburgh')
        , ('GB', 'Glasgow', 'Glasgow City')
        , ('GB', 'Aberdeen', 'Aberdeen City')
        , ('GB', 'Dundee', 'Dundee City')
        , ('GB', 'Inverness', 'Highland')
        , ('GB', 'Belfast', 'Antrim')
        , ('GB', 'Derry', 'Derry and Londonderry')
        , ('GB', 'Lisburn', 'Antrim')
        , ('GB', 'Newry', 'Down')
) AS t(country_code, town_city_name, county_state_name)
;

