DROP TABLE IF EXISTS ref_source_country_name_mapping
;
CREATE TABLE ref_source_country_name_mapping
    AS
SELECT
       *
  FROM (VALUES
         ('ABU DHABI'              , 'AE')
       , ('ALBANIA'                , 'AL')
       , ('ALGERIA'                , 'DZ')
       , ('AMSTERDAM'              , 'NL')
       , ('ARGENTINA'              , 'AR')
       , ('AUSTRALIA'              , 'AU')
       , ('AUSTRIA'                , 'AT')
       , ('AUSTRIA,'               , 'AT')
       , ('BELGIUM'                , 'BE')
       , ('BERMUDA'                , 'BM')
       , ('BOSNIA AND HERZEGOVINA' , 'BA')
       , ('BRAZIL'                 , 'BR')
       , ('BULGARIA'               , 'BG')
       , ('CAMEROON'               , 'CM')
       , ('CANADA'                 , 'CA')
       , ('CANANDA'                , 'CA')
       , ('CAYMAN ISLANDS'         , 'KY')
       , ('CHANNEL ISLANDS'        , 'JE')
       , ('CHILE'                  , 'CL')
       , ('CHINA'                  , 'CN')
       , ('COSTA RICA'             , 'CR')
       , ('COTE D''IVOIRE'         , 'CI')
       , ('CROATIA'                , 'HR')
       , ('CYPRUS'                 , 'CY')
       , ('CZECH REP'              , 'CZ')
       , ('CZECH REPUBLIC'         , 'CZ')
       , ('DENMARK'                , 'DK')
       , ('DOMINICAN REPUBLIC'     , 'DO')
       , ('ECUADOR'                , 'EC')
       , ('ENGLAND'                , 'GB')
       , ('ESTONIA'                , 'EE')
       , ('FINLAND'                , 'FI')
       , ('FRANCE'                 , 'FR')
       , ('FRANCE,'                , 'FR')
       , ('GEORGIA'                , 'GE')
       , ('GERMANY'                , 'DE')
       , ('GERMANY,'               , 'DE')
       , ('GIBRALTAR'              , 'GI')
       , ('GREAT BRITAIN'          , 'GB')
       , ('GREECE'                 , 'GR')
       , ('GUERNSEY'               , 'GG')
       , ('HELSINKI'               , 'FI')
       , ('HONG KONG'              , 'HK')
       , ('HONG KONG (SAR)'        , 'HK')
       , ('HONG KONG,'             , 'HK')
       , ('HUNGARY'                , 'HU')
       , ('ICELAND'                , 'IS')
       , ('ILFOV'                  , 'RO')
       , ('INDIA'                  , 'IN')
       , ('INDONESIA'              , 'ID')
       , ('IRELAND'                , 'IE')
       , ('ISLE OF MAN'            , 'IM')
       , ('ISRAEL'                 , 'IL')
       , ('ITALY'                  , 'IT')
       , ('IVORY COAST'            , 'CI')
       , ('JAMAICA'                , 'JM')
       , ('JAPAN'                  , 'JP')
       , ('JERSEY'                 , 'JE')
       , ('KAZAKHSTAN'             , 'KZ')
       , ('KOREA'                  , 'KR')
       , ('LATVIA'                 , 'LV')
       , ('LESOTHO'                , 'LS')
       , ('LITHUANIA'              , 'LT')
       , ('LONDON'                 , 'GB')
       , ('LUXEMBOURG'             , 'LU')
       , ('MACEDONIA, FYRO'        , 'MK')
       , ('MALAYSIA'               , 'MY')
       , ('MALTA'                  , 'MT')
       , ('MEXICO'                 , 'MX')
       , ('MIDDX'                  , 'GB')
       , ('MONACO'                 , 'MC')
       , ('MOROCCO'                , 'MA')
       , ('NETHERLAND'             , 'NL')
       , ('NETHERLANDS'            , 'NL')
       , ('NEW ZEALAND'            , 'NZ')
       , ('NIGERIA'                , 'NG')
       , ('NORTHERN IRELAND'       , 'GB')
       , ('NORWAY'                 , 'NO')
       , ('NORWAY,'                , 'NO')
       , ('OTHER 1'                , NULL)
       , ('PARAGUAY'               , 'PY')
       , ('PHILIPPINES'            , 'PH')
       , ('POL;AND'                , 'PL')
       , ('POLAND'                 , 'PL')
       , ('PORTUGAL'               , 'PT')
       , ('PUERTO RICO'            , 'PR')
       , ('QATAR'                  , 'QA')
       , ('ROMANIA'                , 'RO')
       , ('SAUDI ARABIA'           , 'SA')
       , ('SCOTLAND'               , 'GB')
       , ('SENEGAL'                , 'SN')
       , ('SERBIA'                 , 'RS')
       , ('SINGAPORE'              , 'SG')
       , ('SLOVAKIA'               , 'SK')
       , ('SLOVENIA'               , 'SI')
       , ('SOUTH AFRICA'           , 'ZA')
       , ('SPAIN'                  , 'ES')
       , ('SWEDEN'                 , 'SE')
       , ('SWITZERLAND'            , 'CH')
       , ('SWITZERLAND,'           , 'CH')
       , ('THAILAND'               , 'TH')
       , ('THE NETHERLANDS'        , 'NL')
       , ('TRINIDAD AND TOBAGO'    , 'TT')
       , ('TURKEY'                 , 'TR')
       , ('UAE'                    , 'AE')
       , ('UK'                     , 'GB')
       , ('UKRAINE'                , 'UA')
       , ('UNITED ARAB EMIRATES'   , 'AE')
       , ('UNITED KINGDOM'         , 'GB')
       , ('UNITED KINGDON'         , 'GB')
       , ('UNITED STATES'          , 'US')
       , ('UNITEDKINGDOM'          , 'GB')
       , ('URUGUAY'                , 'UY')
       , ('USA'                    , 'US')
       , ('WALES'                  , 'GB')
       ) AS t(source_country_name, country_code)
;
