DROP TABLE IF EXISTS ref_country_county_state_mapping
;
CREATE TABLE ref_country_county_state_mapping
    AS
SELECT *
  FROM (VALUES
        -- =====================================================================
        -- United Kingdom (GB) - ONS 2021 Boundaries
        -- =====================================================================
        -- ---------------------------------------------------------------------
        -- England: Non-Metropolitan Counties (current)
        -- ---------------------------------------------------------------------
          ('GB', 'Cambridgeshire',                       'current')
        , ('GB', 'Cumbria',                              'current')
        , ('GB', 'Derbyshire',                           'current')
        , ('GB', 'Devon',                                'current')
        , ('GB', 'Dorset',                               'current')
        , ('GB', 'East Sussex',                          'current')
        , ('GB', 'Essex',                                'current')
        , ('GB', 'Gloucestershire',                      'current')
        , ('GB', 'Hampshire',                            'current')
        , ('GB', 'Hertfordshire',                        'current')
        , ('GB', 'Kent',                                 'current')
        , ('GB', 'Lancashire',                           'current')
        , ('GB', 'Leicestershire',                       'current')
        , ('GB', 'Lincolnshire',                         'current')
        , ('GB', 'Norfolk',                              'current')
        , ('GB', 'North Yorkshire',                      'current')
        , ('GB', 'Nottinghamshire',                      'current')
        , ('GB', 'Oxfordshire',                          'current')
        , ('GB', 'Somerset',                             'current')
        , ('GB', 'Staffordshire',                        'current')
        , ('GB', 'Suffolk',                              'current')
        , ('GB', 'Surrey',                               'current')
        , ('GB', 'Warwickshire',                         'current')
        , ('GB', 'West Sussex',                          'current')
        , ('GB', 'Worcestershire',                       'current')
        -- ---------------------------------------------------------------------
        -- England: Metropolitan Counties (current - retained for statistics)
        -- ---------------------------------------------------------------------
        , ('GB', 'Manchester',                           'current')
        , ('GB', 'Merseyside',                           'current')
        , ('GB', 'South Yorkshire',                      'current')
        , ('GB', 'Tyne and Wear',                        'current')
        , ('GB', 'West Midlands',                        'current')
        , ('GB', 'West Yorkshire',                       'current')
        -- ---------------------------------------------------------------------
        -- England: Unitary Authorities (outside London, current)
        -- ---------------------------------------------------------------------
        , ('GB', 'Bath and North East Somerset',         'current')
        , ('GB', 'Blackburn with Darwen',                'current')
        , ('GB', 'Blackpool',                            'current')
        , ('GB', 'Bracknell Forest',                     'current')
        , ('GB', 'Brighton and Hove',                    'current')
        , ('GB', 'Buckinghamshire',                      'current')
        , ('GB', 'Bristol, City of',                     'current')
        , ('GB', 'Kingston upon Hull, City of',          'current')
        , ('GB', 'Cornwall',                             'current')
        , ('GB', 'Durham',                               'current')
        , ('GB', 'Herefordshire',                        'current')
        , ('GB', 'Darlington',                           'current')
        , ('GB', 'Derby',                                'current')
        , ('GB', 'East Riding of Yorkshire',             'current')
        , ('GB', 'Halton',                               'current')
        , ('GB', 'Hartlepool',                           'current')
        , ('GB', 'Isle of Wight',                        'current')
        , ('GB', 'Isles of Scilly',                      'current')
        , ('GB', 'Leicester',                            'current')
        , ('GB', 'Luton',                                'current')
        , ('GB', 'Medway',                               'current')
        , ('GB', 'Middlesbrough',                        'current')
        , ('GB', 'Milton Keynes',                        'current')
        , ('GB', 'North East Lincolnshire',              'current')
        , ('GB', 'North Lincolnshire',                   'current')
        , ('GB', 'North Somerset',                       'current')
        , ('GB', 'Northumberland',                       'current')
        , ('GB', 'Nottingham',                           'current')
        , ('GB', 'Peterborough',                         'current')
        , ('GB', 'Plymouth',                             'current')
        , ('GB', 'Portsmouth',                           'current')
        , ('GB', 'Reading',                              'current')
        , ('GB', 'Redcar and Cleveland',                 'current')
        , ('GB', 'Rutland',                              'current')
        , ('GB', 'Shropshire',                           'current')
        , ('GB', 'Slough',                               'current')
        , ('GB', 'South Gloucestershire',                'current')
        , ('GB', 'Southampton',                          'current')
        , ('GB', 'Southend-on-Sea',                      'current')
        , ('GB', 'Stockton-on-Tees',                     'current')
        , ('GB', 'Stoke-on-Trent',                       'current')
        , ('GB', 'Swindon',                              'current')
        , ('GB', 'Telford and Wrekin',                   'current')
        , ('GB', 'Thurrock',                             'current')
        , ('GB', 'Torbay',                               'current')
        , ('GB', 'Warrington',                           'current')
        , ('GB', 'West Berkshire',                       'current')
        , ('GB', 'Wiltshire',                            'current')
        , ('GB', 'Windsor and Maidenhead',               'current')
        , ('GB', 'Wokingham',                            'current')
        , ('GB', 'York',                                 'current')
        -- ---------------------------------------------------------------------
        -- England: London Boroughs (32) + City of London (current)
        -- ---------------------------------------------------------------------
        , ('GB', 'Barking and Dagenham',                 'current')
        , ('GB', 'Barnet',                               'current')
        , ('GB', 'Bexley',                               'current')
        , ('GB', 'Brent',                                'current')
        , ('GB', 'Bromley',                              'current')
        , ('GB', 'Camden',                               'current')
        , ('GB', 'London, City of',                      'current')
        , ('GB', 'Croydon',                              'current')
        , ('GB', 'Ealing',                               'current')
        , ('GB', 'Enfield',                              'current')
        , ('GB', 'Greenwich',                            'current')
        , ('GB', 'Hackney',                              'current')
        , ('GB', 'Hammersmith and Fulham',               'current')
        , ('GB', 'Haringey',                             'current')
        , ('GB', 'Harrow',                               'current')
        , ('GB', 'Havering',                             'current')
        , ('GB', 'Hillingdon',                           'current')
        , ('GB', 'Hounslow',                             'current')
        , ('GB', 'Islington',                            'current')
        , ('GB', 'Kensington and Chelsea',               'current')
        , ('GB', 'Kingston upon Thames',                 'current')
        , ('GB', 'Lambeth',                              'current')
        , ('GB', 'Lewisham',                             'current')
        , ('GB', 'Merton',                               'current')
        , ('GB', 'Newham',                               'current')
        , ('GB', 'Redbridge',                            'current')
        , ('GB', 'Richmond upon Thames',                 'current')
        , ('GB', 'Southwark',                            'current')
        , ('GB', 'Sutton',                               'current')
        , ('GB', 'Tower Hamlets',                        'current')
        , ('GB', 'Waltham Forest',                       'current')
        , ('GB', 'Wandsworth',                           'current')
        , ('GB', 'Westminster',                          'current')
        -- ---------------------------------------------------------------------
        -- Wales: 22 Principal Areas (current)
        -- ---------------------------------------------------------------------
        , ('GB', 'Blaenau Gwent',                        'current')
        , ('GB', 'Bridgend',                             'current')
        , ('GB', 'Caerphilly',                           'current')
        , ('GB', 'Cardiff',                              'current')
        , ('GB', 'Carmarthenshire',                      'current')
        , ('GB', 'Ceredigion',                           'current')
        , ('GB', 'Conwy',                                'current')
        , ('GB', 'Denbighshire',                         'current')
        , ('GB', 'Flintshire',                           'current')
        , ('GB', 'Gwynedd',                              'current')
        , ('GB', 'Isle of Anglesey',                     'current')
        , ('GB', 'Merthyr Tydfil',                       'current')
        , ('GB', 'Monmouthshire',                        'current')
        , ('GB', 'Neath Port Talbot',                    'current')
        , ('GB', 'Newport',                              'current')
        , ('GB', 'Pembrokeshire',                        'current')
        , ('GB', 'Powys',                                'current')
        , ('GB', 'Rhondda Cynon Taff',                   'current')
        , ('GB', 'Swansea',                              'current')
        , ('GB', 'Torfaen',                              'current')
        , ('GB', 'Vale of Glamorgan',                    'current')
        , ('GB', 'Wrexham',                              'current')
        -- ---------------------------------------------------------------------
        -- Scotland: 32 Council Areas (current)
        -- ---------------------------------------------------------------------
        , ('GB', 'Aberdeen City',                        'current')
        , ('GB', 'Aberdeenshire',                        'current')
        , ('GB', 'Angus',                                'current')
        , ('GB', 'Argyll and Bute',                      'current')
        , ('GB', 'Edinburgh, City of',                   'current')
        , ('GB', 'Clackmannanshire',                     'current')
        , ('GB', 'Dumfries and Galloway',                'current')
        , ('GB', 'Dundee City',                          'current')
        , ('GB', 'East Ayrshire',                        'current')
        , ('GB', 'East Dunbartonshire',                  'current')
        , ('GB', 'East Lothian',                         'current')
        , ('GB', 'East Renfrewshire',                    'current')
        , ('GB', 'Eilean Siar',                          'current')
        , ('GB', 'Falkirk',                              'current')
        , ('GB', 'Fife',                                 'current')
        , ('GB', 'Glasgow City',                         'current')
        , ('GB', 'Highland',                             'current')
        , ('GB', 'Inverclyde',                           'current')
        , ('GB', 'Midlothian',                           'current')
        , ('GB', 'Moray',                                'current')
        , ('GB', 'North Ayrshire',                       'current')
        , ('GB', 'North Lanarkshire',                    'current')
        , ('GB', 'Orkney',                               'current')
        , ('GB', 'Perth and Kinross',                    'current')
        , ('GB', 'Renfrewshire',                         'current')
        , ('GB', 'Scottish Borders, The',                'current')
        , ('GB', 'Shetland',                             'current')
        , ('GB', 'South Ayrshire',                       'current')
        , ('GB', 'South Lanarkshire',                    'current')
        , ('GB', 'Stirling',                             'current')
        , ('GB', 'West Dunbartonshire',                  'current')
        , ('GB', 'West Lothian',                         'current')
        -- ---------------------------------------------------------------------
        -- Northern Ireland: Old District Councils (Workday values; pre-2015 reorganisation)
        -- ---------------------------------------------------------------------
        , ('GB', 'Ards',                                 'current')
        , ('GB', 'Ballymena',                            'current')
        , ('GB', 'Ballymoney',                           'current')
        , ('GB', 'Banbridge',                            'current')
        , ('GB', 'Belfast',                              'current')
        , ('GB', 'Carrickfergus',                        'current')
        , ('GB', 'Castlereagh',                          'current')
        , ('GB', 'Coleraine',                            'current')
        , ('GB', 'Cookstown',                            'current')
        , ('GB', 'Derry',                                'current')
        , ('GB', 'Lisburn',                              'current')
        , ('GB', 'Magherafelt',                          'current')
        , ('GB', 'Newtownabbey',                         'current')
        , ('GB', 'Newry and Mourne',                     'current')
        , ('GB', 'Omagh',                                'current')
        -- =====================================================================
        -- United Kingdom (GB) - Historic / Abolished Counties
        -- Useful for matching against legacy records
        -- =====================================================================
        -- ---------------------------------------------------------------------
        -- England: Abolished / reorganised counties (historic)
        -- ---------------------------------------------------------------------
        , ('GB', 'Bedfordshire',                         'historic')   -- → Bedford + Central Bedfordshire (2009)
        , ('GB', 'Berkshire',                            'historic')   -- → 6 UAs (1998)
        , ('GB', 'Cheshire',                             'historic')   -- → Cheshire East + Cheshire West and Chester (2009)
        , ('GB', 'Cleveland',                            'historic')   -- → Hartlepool, Middlesbrough, Stockton-on-Tees, Redcar and Cleveland (1996)
        , ('GB', 'London',                               'historic')   -- → 32 boroughs + City of London; still used colloquially
        , ('GB', 'Northamptonshire',                     'historic')   -- → North + West Northamptonshire (2021)
        -- ---------------------------------------------------------------------
        -- Northern Ireland: 6 Traditional Counties (historic)
        -- ---------------------------------------------------------------------
        , ('GB', 'County Antrim',                        'historic')
        , ('GB', 'County Armagh',                        'historic')
        , ('GB', 'County Down',                          'historic')
        , ('GB', 'County Fermanagh',                     'historic')
        , ('GB', 'County Londonderry',                   'historic')
        , ('GB', 'County Tyrone',                        'historic')
        -- =====================================================================
        -- United States (US): 50 States + District of Columbia (current)
        -- =====================================================================
        , ('US', 'Alabama',                              'current')
        , ('US', 'Alaska',                               'current')
        , ('US', 'Arizona',                              'current')
        , ('US', 'Arkansas',                             'current')
        , ('US', 'California',                           'current')
        , ('US', 'Colorado',                             'current')
        , ('US', 'Connecticut',                          'current')
        , ('US', 'Delaware',                             'current')
        , ('US', 'District of Columbia',                 'current')
        , ('US', 'Florida',                              'current')
        , ('US', 'Georgia',                              'current')
        , ('US', 'Hawaii',                               'current')
        , ('US', 'Idaho',                                'current')
        , ('US', 'Illinois',                             'current')
        , ('US', 'Indiana',                              'current')
        , ('US', 'Iowa',                                 'current')
        , ('US', 'Kansas',                               'current')
        , ('US', 'Kentucky',                             'current')
        , ('US', 'Louisiana',                            'current')
        , ('US', 'Maine',                                'current')
        , ('US', 'Maryland',                             'current')
        , ('US', 'Massachusetts',                        'current')
        , ('US', 'Michigan',                             'current')
        , ('US', 'Minnesota',                            'current')
        , ('US', 'Mississippi',                          'current')
        , ('US', 'Missouri',                             'current')
        , ('US', 'Montana',                              'current')
        , ('US', 'Nebraska',                             'current')
        , ('US', 'Nevada',                               'current')
        , ('US', 'New Hampshire',                        'current')
        , ('US', 'New Jersey',                           'current')
        , ('US', 'New Mexico',                           'current')
        , ('US', 'New York',                             'current')
        , ('US', 'North Carolina',                       'current')
        , ('US', 'North Dakota',                         'current')
        , ('US', 'Ohio',                                 'current')
        , ('US', 'Oklahoma',                             'current')
        , ('US', 'Oregon',                               'current')
        , ('US', 'Pennsylvania',                         'current')
        , ('US', 'Rhode Island',                         'current')
        , ('US', 'South Carolina',                       'current')
        , ('US', 'South Dakota',                         'current')
        , ('US', 'Tennessee',                            'current')
        , ('US', 'Texas',                                'current')
        , ('US', 'Utah',                                 'current')
        , ('US', 'Vermont',                              'current')
        , ('US', 'Virginia',                             'current')
        , ('US', 'Washington',                           'current')
        , ('US', 'West Virginia',                        'current')
        , ('US', 'Wisconsin',                            'current')
        , ('US', 'Wyoming',                              'current')
) AS t(country_code, county_state_name, name_type)
;
