DROP TABLE IF EXISTS stg_fin_phone_number_format
;
CREATE TABLE stg_fin_phone_number_format
    AS
SELECT
       *
  FROM (VALUES
      ('Afghanistan', '93', '2 digits, no special characters', '7 digits only, no special characters', '2-3 digits, no special characters', '6-7 digits only, no special characters'),
      ('Åland Islands', '358', '1-3 digits, no special characters, may be preceded by ''0''', '4-8 digits only, no special characters', '2-4 digits, no special characters, may be preceded by ''0''', '4-8 digits only, no special characters'),
      ('Albania', '355', '1-3 digits, no special characters, may be preceded by ''0''', '4-7 digits only, no special characters', '1-3 digits, no special characters, may be preceded by ''0''', '4-7 digits only, no special characters'),
      ('Algeria', '213', '2 digits, no special characters', '6 digits only, no special characters', '1-3 digits, no special characters', '6-8 digits only, no special characters'),
      ('American Samoa', '1', '3 digits, no special characters', '3 digits + optional dash (or dot) + 4 digits', '3 digits, no special characters', '3 digits + optional dash (or dot) + 4 digits'),
      ('Andorra', '376', 'area code not used', '6 digits only, no special characters', 'area code not used', '6 digits only, no special characters'),
      ('Angola', '244', '2-3 digits, no special characters', '6-7 digits only, no special characters', '2-3 digits, no special characters', '6-7 digits only, no special characters'),
      ('Anguilla', '1', '3 digits, no special characters', '3 digits + optional dash (or dot) + 4 digits', '3 digits, no special characters', '3 digits + optional dash (or dot) + 4 digits'),
      ('Antigua and Barbuda', '1', '3 digits, no special characters', '3 digits + optional dash (or dot) + 4 digits', '3 digits, no special characters', '3 digits + optional dash (or dot) + 4 digits'),
      ('Argentina', '54', '2-4 digits, no special characters, may be preceded by ''0''', '6-8 digits only, no special characters', '2-4 digits, no special characters, may be preceded by ''0''', '6-8 digits only, no special characters'),
      ('Armenia', '374', '2-3 digits, no special characters', '5-6 digits only, no special characters', '2 digits, no special characters', '6 digits only, no special characters'),
      ('Aruba', '297', 'area code not used', '3 digits + optional dash (or dot) + 4 digits', '3 digits, no special characters', '3 digits + optional dash (or dot) + 4 digits'),
      ('Australia', '61', '1 digit, no special characters, may be preceded by ''0''', '8 digits only or 300 and 800 followed by 6 digits or 31, 32, 33 and 34 followed by 3 digits', '1 digit, no special characters, may be preceded by ''0''', '8-9 digits only, no special characters, may be preceded by ''0'''),
      ('Austria', '43', '1-4 digits, no special characters', '4-13 digits only, no special characters', '1-4 digits, no special characters', '4-13 digits only, no special characters'),
      ('Azerbaijan', '994', '2-3 digits, no special characters', '5-7 digits only, no special characters', '2 digits, no special characters', '7 digits only, no special characters'),
      ('Bahamas', '1', '3 digits, no special characters', '3 digits + optional dash (or dot) + 4 digits', '3 digits, no special characters', '3 digits + optional dash (or dot) + 4 digits'),
      ('Bahrain', '973', 'area code not used', '8 digits only, no special characters', 'area code not used', '8 digits only, no special characters'),
      ('Bangladesh', '880', '1-4 digits, no special characters', '3-8 digits only, no special characters', '2-4 digits, no special characters', '4-8 digits only, no special characters'),
      ('Barbados', '1', '3 digits, no special characters', '3 digits + optional dash (or dot) + 4 digits', '3 digits, no special characters', '3 digits + optional dash (or dot) + 4 digits'),
      ('Belarus', '375', '2-4 digits, no special characters', '5-7 digits only, no special characters', '2 digits, no special characters', '7 digits only, no special characters'),
      ('Belgium', '32', '0-2 digits, no special characters, may be preceded by ''0''', '6-9 digits only, no special characters', '0-2 digits, no special characters, may be preceded by ''04''', '6-9 digits only, no special characters'),
      ('Belize', '501', 'area code not used', '7 digits only, no special characters', 'area code not used', '7 digits only, no special characters'),
      ('Benin', '229', '2 digits, no special characters', '6 digits only, no special characters', '2 digits, no special characters', '6 digits only, no special characters'),
      ('Bermuda', '1', '3 digits, no special characters', '3 digits + optional dash (or dot) + 4 digits', '3 digits, no special characters', '3 digits + optional dash (or dot) + 4 digits'),
      ('Bhutan', '975', '1 digit, no special characters', '6 digits only, no special characters', '2 digits, no special characters', '6 digits only, no special characters'),
      ('Bolivia', '591', '1 digit, no special characters', '7 digits only, no special characters', '1 digit, no special characters', '7 digits only, no special characters'),
      ('Bonaire, Sint Eustatius, and Saba', '599', 'area code not used', '7 digits only, no special characters', 'area code not used', '7 digits only, no special characters'),
      ('Bosnia and Herzegovina', '387', '2 digits, no special characters, may be preceded by ''0''', '6 digits only, no special characters', '2 digits, no special characters, may be preceded by ''0''', '6 digits only, no special characters'),
      ('Botswana', '267', 'area code not used', '7 digits only, no special characters', 'area code not used', '8 digits only, no special characters'),
      ('Brazil', '55', '2 digits, no special characters, may be preceded by ''0''', '8-9 digits only, no special characters', '2 digits, no special characters, may be preceded by ''0''', '8-9 digits only, no special characters'),
      ('British Indian Ocean Territory', '246', 'area code not used', '7 digits only, no special characters', 'area code not used', '7 digits only, no special characters'),
      ('British Virgin Islands', '1', '3 digits, no special characters', '3 digits + optional dash (or dot) + 4 digits', '3 digits, no special characters', '3 digits + optional dash (or dot) + 4 digits'),
      ('Brunei', '673', 'area code not used', '7 digits only, no special characters', 'area code not used', '7 digits only, no special characters'),
      ('Bulgaria', '359', '1-5 digits, no special characters, may be preceded by ''0''', '3-7 digits only, no special characters', '2-3 digits, no special characters, may be preceded by ''0''', '6-7 digits only, no special characters'),
      ('Burkina Faso', '226', 'area code not used', '8 digits only, no special characters', 'area code not used', '8 digits only, no special characters'),
      ('Burundi', '257', 'area code not used', '8 digits only, no special characters', 'area code not used', '8 digits only, no special characters'),
      ('Cabo Verde', '238', 'area code not used', '7 digits only, no special characters', 'area code not used', '7 digits only, no special characters'),
      ('Cambodia', '855', '2 digits, no special characters', '6-7 digits only, no special characters', '2 digits, no special characters', '6-7 digits only, no special characters'),
      ('Cameroon', '237', 'area code not used', '8 digits only, no special characters', 'area code not used', '8 digits only, no special characters'),
      ('Canada', '1', '3 digits, no special characters', '3 digits + optional dash (or dot) + 4 digits', '3 digits, no special characters', '3 digits + optional dash (or dot) + 4 digits'),
      ('Cayman Islands', '1', '3 digits, no special characters', '3 digits + optional dash (or dot) + 4 digits', '3 digits, no special characters', '3 digits + optional dash (or dot) + 4 digits'),
      ('Central African Republic', '236', 'area code not used', '6-8 digits only, no special characters', 'area code not used', '8 digits only, no special characters'),
      ('Chad', '235', 'area code not used', '7-8 digits only, no special characters', 'area code not used', '8 digits only, no special characters'),
      ('Chile', '56', '1-2 digits, no special characters', '6-8 digits only, no special characters', '1 digit, no special characters', '8-9 digits only, no special characters'),
      ('China', '86', '1-4 digits, no special characters', '3-4 digits + optional dash + 3-7 digits', '1-4 digits, no special characters', '3-4 digits + optional dash + 3-7 digits'),
      ('Christmas Island', '61', '1 digit, no special characters, may be preceded by ''0''', '8 digits only, no special characters', '1 digit, no special characters, may be preceded by ''0''', '8-9 digits only, no special characters, may be preceded by ''0'''),
      ('Cocos (Keeling) Islands', '61', '1 digit, no special characters, may be preceded by ''0''', '8 digits only, no special characters', '1 digit, no special characters, may be preceded by ''0''', '8-9 digits only, no special characters, may be preceded by ''0'''),
      ('Colombia', '57', '1-3 digits, no special characters', '7 digits only, no special characters', '3 digits, no special characters', '7 digits only, no special characters'),
      ('Comoros', '269', 'area code not used', '7 digits only, no special characters', 'area code not used', '7 digits only, no special characters'),
      ('Congo', '242', '2-4 digits, no special characters', '5-7 digits only, no special characters', '2 digits, no special characters', '7 digits only, no special characters'),
      ('Congo, Democratic Republic of the', '243', '1 digit, no special characters', '6-7 digits only, no special characters', '1-2 digits, no special characters', '6-7 digits only, no special characters'),
      ('Cook Islands', '682', 'area code not used', '5 digits only, no special characters', 'area code not used', '5 digits only, no special characters'),
      ('Costa Rica', '506', 'area code not used', '8 digits only, no special characters', 'area code not used', '8 digits only, no special characters'),
      ('Côte d''Ivoire', '225', 'area code not used', '8 digits only, no special characters', 'area code not used', '8 digits only, no special characters'),
      ('Croatia', '385', '1-2 digits, no special characters, may be preceded by ''0''', '6-7 digits, no special characters', '1-2 digits, no special characters, may be preceded by ''0''', '6-7 digits, no special characters'),
      ('Cuba', '53', '1-4 digits, no special characters', '4-7 digits only, no special characters', '1-4 digits, no special characters', '4-7 digits only, no special characters'),
      ('Curaçao', '599', '1 digit, no special characters', '7-8 digits only, no special characters', '1 digit, no special characters', '7-8 digits only, no special characters'),
      ('Cyprus', '357', '2 digits, no special characters', '6 digits only, no special characters', '2 digits, no special characters', '6 digits only, no special characters'),
      ('Czechia', '420', '1-3 digits, no special characters', '6-8 digits only, no special characters', '1-3 digits, no special characters', '6-9 digits only, no special characters'),
      ('Denmark', '45', 'area code not used', '8 digits only, no special characters', 'area code not used', '8 digits only, no special characters'),
      ('Djibouti', '253', 'area code not used', '6 or 8 digits only, no special characters', 'area code not used', '8 digits only, no special characters'),
      ('Dominica', '1', '3 digits, no special characters', '3 digits + optional dash (or dot) + 4 digits', '3 digits, no special characters', '3 digits + optional dash (or dot) + 4 digits'),
      ('Dominican Republic', '1', '3 digits, no special characters', '3 digits + optional dash (or dot) + 4 digits', '3 digits, no special characters', '3 digits + optional dash (or dot) + 4 digits'),
      ('Ecuador', '593', '1 digit, no special characters', '7 digits only, no special characters', '2 digits, no special characters', '7 digits only, no special characters'),
      ('Egypt', '20', '1-2 digits, no special characters, may be preceded by ''0''', '7-8 digits only, no special characters', '1-3 digits, no special characters, may be preceded by ''0''', '7-8 digits only, no special characters'),
      ('El Salvador', '503', 'area code not used', '8 digits only, no special characters', 'area code not used', '8 digits only, no special characters'),
      ('Equatorial Guinea', '240', '2 digits, no special characters', '6-7 digits only, no special characters', '2 digits, no special characters', '7 digits only, no special characters'),
      ('Eritrea', '291', '1 digit, no special characters', '6 digits only, no special characters', '1 digit, no special characters', '6 digits only, no special characters'),
      ('Estonia', '372', '1-2 digits, no special characters', '5-8 digits only, no special characters', '1-2 digits, no special characters', '5-8 digits only, no special characters'),
      ('Ethiopia', '251', '2 digits, no special characters', '7 digits only, no special characters', '2 digits, no special characters', '7 digits only, no special characters'),
      ('Falkland Islands', '500', 'area code not used', '5 digits only, no special characters', 'area code not used', '5 digits only, no special characters'),
      ('Faroe Islands', '298', 'area code not used', '6 digits only, no special characters', 'area code not used', '6 digits only, no special characters'),
      ('Fiji', '679', 'area code not used', '7 digits only, no special characters', 'area code not used', '7 digits only, no special characters'),
      ('Finland', '358', '1-3 digits, no special characters, may be preceded by ''0''', '4-8 digits only, no special characters', '2-4 digits, no special characters, may be preceded by ''0''', '4-8 digits only, no special characters'),
      ('France', '33', '1 digit, may be preceded by ''0''', '8-10 digits only, no special characters', '1 digit, may be preceded by ''0''', '8-10 digits only, no special characters'),
      ('French Guiana', '594', 'area code not used', '6 digits only, no special characters', '3 digits, no special characters', '6 digits only, no special characters'),
      ('French Polynesia', '689', 'area code not used', '6 digits only, no special characters', 'area code not used', '6 digits only, no special characters'),
      ('Gabon', '241', 'area code not used', '6-7 digits only, no special characters', 'area code not used', '7 digits only, no special characters'),
      ('Gambia', '220', 'area code not used', '7 digits only, no special characters', 'area code not used', '7 digits only, no special characters'),
      ('Georgia', '995', '2-3 digits, no special characters', '5-6 digits only, no special characters', '2-3 digits, no special characters', '5-6 digits only, no special characters'),
      ('Germany', '49', '2-5 digits, no special characters, may be preceded by ''0''', '3-11 digits only, no special characters', '2-4 digits, no special characters, may be preceded by ''0''', '6-11 digits only, no special characters'),
      ('Ghana', '233', '2-3 digits, no special characters', '3-7 digits only, no special characters', '2-3 digits, no special characters', '3-7 digits only, no special characters'),
      ('Gibraltar', '350', 'area code not used', '8 digits only, no special characters', 'area code not used', '8 digits only, no special characters'),
      ('Greece', '30', '2-4 digits, no special characters', '6-8 digits only, no special characters', '3 digits, no special characters', '7 digits only, no special characters'),
      ('Greenland', '299', 'area code not used', '6 digits only, no special characters', 'area code not used', '6 digits only, no special characters'),
      ('Grenada', '1', '3 digits, no special characters', '3 digits + optional dash (or dot) + 4 digits', '3 digits, no special characters', '3 digits + optional dash (or dot) + 4 digits'),
      ('Guadeloupe', '590', '3-4 digits, no special characters', '6 digits only, no special characters', '3-4 digits, no special characters', '6 digits only, no special characters'),
      ('Guam', '1', '3 digits, no special characters', '3 digits + optional dash (or dot) + 4 digits', '3 digits, no special characters', '3 digits + optional dash (or dot) + 4 digits'),
      ('Guatemala', '502', 'area code not used', '8 digits only, no special characters', 'area code not used', '8 digits only, no special characters'),
      ('Guernsey', '44', '2-5 digits, no special characters, may be preceded by ''0''', '4-8 digits only, no special characters', '2-5 digits, no special characters, may be preceded by ''0''', '4-8 digits only, no special characters'),
      ('Guinea', '224', 'area code not used', '8 digits only, no special characters', 'area code not used', '8 digits only, no special characters'),
      ('Guinea-Bissau', '245', 'area code not used', '7 digits only, no special characters', 'area code not used', '7 digits only, no special characters'),
      ('Guyana', '592', '3 digits, no special characters', '4 digits only, no special characters', '3 digits, no special characters', '4 digits only, no special characters'),
      ('Haiti', '509', 'area code not used', '7-8 digits only, no special characters', 'area code not used', '8 digits only, no special characters'),
      ('Holy See (Vatican City State)', '39', '1-3 digits, no special characters, may be preceded by ''0''', '5-8 digits only, no special characters', '3 digits, no special characters', '6-8 digits only, no special characters'),
      ('Honduras', '504', 'area code not used', '8 digits only, no special characters', 'area code not used', '8 digits only, no special characters'),
      ('Hong Kong', '852', 'area code not used', '8 digits only, no special characters', 'area code not used', '8 digits only, no special characters'),
      ('Hungary', '36', '1-2 digits, no special characters', '6-7 digits only, no special characters', '2 digits, no special characters', '7 digits only, no special characters'),
      ('Iceland', '354', 'area code not used', '7 digits only, no special characters', 'area code not used', '7 digits only, no special characters'),
      ('India', '91', '2-4 digits, no special characters', '6-10 digits only, no special characters', '2-4 digits, no special characters', '6-10 digits only, no special characters'),
      ('Indonesia', '62', '2-4 digits, no special characters, may be preceded by ''0''', '6-12 digits only, no special characters', '2-4 digits, no special characters, may be preceded by ''0''', '6-12 digits only, no special characters'),
      ('Iran', '98', '2-3 digits, no special characters, may be preceded by ''0''', '7-8 digits only, no special characters', '3 digits, no special characters, may be preceded by ''0''', '7 digits only, no special characters'),
      ('Iraq', '964', '1-4 digits, no special characters', '6-7 digits only, no special characters', '3-4 digits only, no special characters', '7 digits only, no special characters'),
      ('Ireland', '353', '1-3 digits, no special characters, may be preceded by ''0''', '5-7 digits only, no special characters', '2 digits, no special characters, may be preceded by ''0''', '5-7 digits only, no special characters'),
      ('Isle of Man', '44', '2-5 digits, no special characters, may be preceded by ''0''', '4-8 digits only, no special characters', '2-5 digits, no special characters, may be preceded by ''0''', '4-8 digits only, no special characters'),
      ('Israel', '972', '1-2 digits, no special characters, may be preceded by ''0''', '7 digits only, no special characters', '2 digits, no special characters, may be preceded by ''0''', '7 digits only, no special characters'),
      ('Italy', '39', '1-3 digits, no special characters, may be preceded by ''0''', '5-8 digits only, no special characters', '3 digits, no special characters', '6-8 digits only, no special characters'),
      ('Jamaica', '1', '3 digits, no special characters', '3 digits + optional dash (or dot) + 4 digits', '3 digits, no special characters', '3 digits + optional dash (or dot) + 4 digits'),
      ('Japan', '81', '1-5 digits, no special characters, may be preceded by ''0''', '2-4 digits + optional dash + 2-4 digits', '1-4 digits, no special characters, may be preceded by ''0''', '2-4 digits + optional dash + 2-4 digits'),
      ('Jersey', '44', '2-5 digits, no special characters, may be preceded by ''0''', '4-8 digits only, no special characters', '2-5 digits, no special characters, may be preceded by ''0''', '4-8 digits only, no special characters'),
      ('Jordan', '962', '1-2 digits, no special characters', '7 digits only, no special characters', '1-2 digits, no special characters', '7-8 digits only, no special characters'),
      ('Kazakhstan', '7', '3 digits, no special characters', '7 digits only, no special characters', '3 digits, no special characters', '7 digits only, no special characters'),
      ('Kenya', '254', '2 digits, no special characters', '5-7 digits only, no special characters', '3 digits, no special characters', '6 digits only, no special characters'),
      ('Kiribati', '686', 'area code not used', '5 digits only, no special characters', 'area code not used', '5 digits only, no special characters'),
      ('Korea, Democratic People''s Republic of', '850', '1-3 digits, no special characters, may be preceded by ''0''', '5-8 digits only, no special characters', '1-3 digits, no special characters, may be preceded by ''0''', '5-8 digits only, no special characters'),
      ('Korea, Republic of', '82', '1-3 digits, no special characters', '7-8 digits only, no special characters', '1-3 digits, no special characters', '7-8 digits only, no special characters'),
      ('Kosovo', '386, 381, 377, or 383', '0-3 digits, no special characters', '5-8 digits only, no special characters', '0-3 digits, no special characters', '5-8 digits only, no special characters'),
      ('Kuwait', '965', 'area code not used', '8 digits only, no special characters', 'area code not used', '8 digits only, no special characters'),
      ('Kyrgyzstan', '996', '3-4 digits, no special characters', '5-6 digits only, no special characters', '3-4 digits, no special characters', '5-6 digits only, no special characters'),
      ('Laos', '856', '2 digits, no special characters', '6-8 digits only, no special characters', '2 digits, no special characters', '6-8 digits only, no special characters'),
      ('Latvia', '371', '1-3 digits, no special characters', '5-7 digits only, no special characters', '1-3 digits, no special characters', '5-8 digits only, no special characters'),
      ('Lebanon', '961', '1-2 digits, no special characters', '6 digits only, no special characters', '1-2 digits, no special characters', '6 digits only, no special characters'),
      ('Lesotho', '266', 'area code not used', '8 digits only, no special characters', 'area code not used', '8 digits only, no special characters'),
      ('Liberia', '231', 'area code not used', '6 or 8 digits only, no special characters', 'area code not used', '7-8 digits only, no special characters'),
      ('Libya', '218', '2-3 digits, no special characters', '5-7 digits only, no special characters', '2-3 digits, no special characters', '5-7 digits only, no special characters'),
      ('Liechtenstein', '423', 'area code not used', '7 digits only, no special characters', 'area code not used', '7 digits only, no special characters'),
      ('Lithuania', '370', '1-3 digits, no special characters', '5-7 digits only, no special characters', '1-3 digits, no special characters', '5-7 digits only, no special characters'),
      ('Luxembourg', '352', '1-3 digits, no special characters', '4-7 digits only, no special characters', '1-3 digits, no special characters', '4-7 digits only, no special characters'),
      ('Macao', '853', 'area code not used', '8 digits only, no special characters', 'area code not used', '8 digits only, no special characters'),
      ('Macedonia, the Former Yugoslav Republic of', '389', '1-2 digits, no special characters, may be preceded by ''0''', '6-7 digits only, no special characters', '2 digits, no special characters, may be preceded by ''0''', '6 digits only, no special characters'),
      ('Madagascar', '261', '2-4 digits, no special characters', '5 digits only, no special characters', '2-4 digits, no special characters', '5 digits only, no special characters'),
      ('Malawi', '265', 'area code not used', '7-9 digits only, no special characters', 'area code not used', '7-9 digits only, no special characters'),
      ('Malaysia', '60', '1-2 digits, no special characters, may be preceded by ''0''', '6-8 digits only, no special characters', '1-2 digits, no special characters, may be preceded by ''0''', '6-10 digits only, no special characters, may be preceded by ''0'''),
      ('Maldives', '960', 'area code not used', '7 digits only, no special characters', 'area code not used', '7 digits only, no special characters'),
      ('Mali', '223', 'area code not used', '8 digits only, no special characters', 'area code not used', '8 digits only, no special characters'),
      ('Malta', '356', 'area code not used', '8 digits only, no special characters', 'area code not used', '8 digits only, no special characters'),
      ('Marshall Islands', '692', 'area code not used', '7 digits only, no special characters', 'area code not used', '7 digits only, no special characters'),
      ('Martinique', '596', '3-4 digits, no special characters', '6 digits only, no special characters', '3-4 digits, no special characters', '6 digits only, no special characters'),
      ('Mauritania', '222', 'area code not used', '7-8 digits only, no special characters', 'area code not used', '7 digits only, no special characters'),
      ('Mauritius', '230', 'area code not used', '7 digits only, no special characters', 'area code not used', '7-8 digits only, no special characters'),
      ('Mayotte', '262', '3 digits, no special characters', '6 digits only, no special characters', '3 digits, no special characters', '6 digits only, no special characters'),
      ('Mexico', '52', '2-3 digits, no special characters', '3 digits + optional dash + 4-7 digits', '2-3 digits, no special characters', '3 digits + optional dash + 4-7 digits'),
      ('Micronesia, Federated States of', '691', 'area code not used', '7 digits only, no special characters', 'area code not used', '7 digits only, no special characters'),
      ('Moldova', '373', '2-3 digits, no special characters', '5-6 digits only, no special characters', '2-3 digits, no special characters', '5-6 digits only, no special characters'),
      ('Monaco', '377', 'area code not used', '8 digits only, no special characters', 'area code not used', '8 digits only, no special characters'),
      ('Mongolia', '976', '1-4 digits, no special characters', '4-7 digits only, no special characters', '1-4 digits, no special characters', '4-8 digits only, no special characters'),
      ('Montenegro', '382', '2 digits, no special characters', '6 digits only, no special characters', '2 digits, no special characters', '6 digits only, no special characters'),
      ('Montserrat', '1', '3 digits, no special characters', '7 digits only, no special characters', '3 digits, no special characters', '7 digits only, no special characters'),
      ('Morocco', '212', 'area code not used', '9 digits only, no special characters', 'area code not used', '9 digits only, no special characters'),
      ('Mozambique', '258', '2-3 digits, no special characters', '5-6 digits only, no special characters', '2-3 digits, no special characters', '5-7 digits only, no special characters'),
      ('Myanmar', '95', '1-2 digits, no special characters', '5-7 digits only, no special characters', '1-2 digits, no special characters', '5-9 digits only, no special characters'),
      ('Namibia', '264', '2-4 digits, no special characters', '4-6 digits only, no special characters', '2-3 digits, no special characters', '7 digits only, no special characters'),
      ('Nauru', '674', 'area code not used', '7 digits only, no special characters', 'area code not used', '7 digits only, no special characters'),
      ('Nepal', '977', '1-2 digits, no special characters', '6-7 digits only, no special characters', '1-2 digits, no special characters', '6-7 digits only, no special characters'),
      ('Netherlands', '31', '2-3 digits, no special characters, may be preceded by ''0''', '6-8 digits only, no special characters', '2-3 digits (or 1 digit if the digit is ''6''), no special characters, may be preceded by ''06''', '6-8 digits only, no special characters'),
      ('New Caledonia', '687', 'area code not used', '6 digits only, no special characters', 'area code not used', '6 digits only, no special characters'),
      ('New Zealand', '64', '1-2 digits, no special characters, may be preceded by ''0''', '6-8 digits only, no special characters', '2 digits, no special characters, may be preceded by ''0''', '6-8 digits only, no special characters'),
      ('Nicaragua', '505', 'area code not used', '8 digits only, no special characters', 'area code not used', '8 digits only, no special characters'),
      ('Niger', '227', '2 digits, no special characters', '6 digits only, no special characters', '2 digits, no special characters', '6 digits only, no special characters'),
      ('Nigeria', '234', '1-2 digits, no special characters', '5-7 digits only, no special characters', '1-3 digits, no special characters', '5-7 digits only, no special characters'),
      ('Niue', '683', '0 or 1 digits', '3 or 4 digits', '0 or 1 digits', '3 or 4 digits'),
      ('Norfolk Island', '672', 'up to 2 digits, no special characters', '^\d{4,5}$', 'up to 2 digits, no special characters', '4 or 5 digits only, no special characters'),
      ('Northern Mariana Islands', '1', '3 digits, no special characters', '3 digits + optional dash (or dot) + 4 digits', '3 digits, no special characters', '3 digits + optional dash (or dot) + 4 digits'),
      ('Norway', '47', 'area code not used', '8 digits only, no special characters', 'area code not used', '8 digits only, no special characters'),
      ('Oman', '968', 'area code not used', '8 digits only, no special characters', 'area code not used', '8 digits only, no special characters'),
      ('Pakistan', '92', '2-3 digits, no special characters, may be preceded by ''0''', '6-8 digits only, no special characters', '2-3 digits, no special characters, may be preceded by ''0''', '7-8 digits only, no special characters'),
      ('Palau', '680', 'area code not used', '7 digits only, no special characters', 'area code not used', '7 digits only, no special characters'),
      ('Palestine', '970', '1-2 digits, no special characters, may be preceded by ''0''', '7 digits only, no special characters', '2 digits, no special characters, may be preceded by ''0''', '7 digits only, no special characters'),
      ('Panama', '507', 'area code not used', '7-8 digits only, no special characters', 'area code not used', '7-8 digits only, no special characters'),
      ('Papua New Guinea', '675', 'area code not used', '7 digits only, no special characters', 'area code not used', '8 digits only, no special characters'),
      ('Paraguay', '595', '2-3 digits, no special characters', '6-7 digits only, no special characters', '2-3 digits, no special characters', '6-7 digits only, no special characters'),
      ('Peru', '51', '1-2 digits, no special characters', '6-8 digits only, no special characters', '1-2 digits, no special characters', '7-9 digits only, no special characters'),
      ('Philippines', '63', '1-3 digits, no special characters', '7 digits only, no special characters', '3-4 digits, no special characters', '7 digits only, no special characters'),
      ('Pitcairn Islands', '64', 'area code not used', '8 digits only, no special characters', 'area code not used', '8 digits only, no special characters'),
      ('Poland', '48', '2 digits, no special characters, may be preceded by ''0''', '7 or 9 digits only, no special characters', '2 digits, no special characters, may be preceded by ''0''', '7 or 9 digits only, no special characters'),
      ('Portugal', '351', '2-3 digits, no special characters', '6-7 digits only, no special characters', '2-3 digits, no special characters', '6-7 digits only, no special characters'),
      ('Puerto Rico', '1', '3 digits, no special characters', '3 digits + optional dash (or dot) + 4 digits', '3 digits, no special characters', '3 digits + optional dash (or dot) + 4 digits'),
      ('Qatar', '974', 'area code not used', '7-8 digits only, no special characters', 'area code not used', '8 digits only, no special characters'),
      ('Reunion', '262', '3 digits, no special characters', '6 digits only, no special characters', '3 digits, no special characters', '6 digits only, no special characters'),
      ('Romania', '40', '2-3 digits, no special characters, may be preceded by ''0''', '6-7 digits only, no special characters', '2-3 digits, no special characters, may be preceded by ''0''', '6-7 digits only, no special characters'),
      ('Russian Federation', '7', '3-4 digits, no special characters', '5-7 digits only, no special characters', '3-4 digits, no special characters', '5-7 digits only, no special characters'),
      ('Rwanda', '250', 'area code not used', '9 digits only, no special characters', 'area code not used', '9 digits only, no special characters'),
      ('Saint Barthelemy', '590', '3 digits, no special characters', '6 digits only, no special characters', '3 digits, no special characters', '6 digits only, no special characters'),
      ('Saint Helena, Ascension and Tristan da Cunha', '247 or 290', '1-3 digits, no special characters', '3 to 5 digits or 8 digits, no special characters', '1-3 digits, no special characters', '3 to 5 digits, no special characters'),
      ('Saint Kitts and Nevis', '869', '3 digits, no special characters', '3 digits + optional dash (or dot) + 4 digits', '3 digits, no special characters', '3 digits + optional dash (or dot) + 4 digits'),
      ('Saint Lucia', '1', '3 digits, no special characters', '3 digits + optional dash (or dot) + 4 digits', '3 digits, no special characters', '3 digits + optional dash (or dot) + 4 digits'),
      ('Saint Martin', '590', '3 digits, no special characters', '6 digits only, no special characters', '3 digits, no special characters', '6 digits only, no special characters'),
      ('Saint Pierre and Miquelon', '508', '3 digits, no special characters', '6 digits only, no special characters', '3 digits, no special characters', '6 digits only, no special characters'),
      ('Saint Vincent and the Grenadines', '1', '3 digits, no special characters', '3 digits + optional dash (or dot) + 4 digits', '3 digits, no special characters', '3 digits + optional dash (or dot) + 4 digits'),
      ('Samoa', '685', 'area code not used', '5 digits only, no special characters', 'area code not used', '7 digits only, no special characters'),
      ('Saint Martin', '378', 'area code not used', '10 digits only, no special characters', 'area code not used', '10 digits only, no special characters'),
      ('Sao Tome and Principe', '239', 'area code not used', '6 digits only, no special characters', 'area code not used', '6 digits only, no special characters'),
      ('Saudi Arabia', '966', '1-2 digits, no special characters', '7 digits only, no special characters', '2 digits, no special characters', '7 digits only, no special characters'),
      ('Senegal', '221', 'area code not used', '9 digits only, no special characters', 'area code not used', '9 digits only, no special characters'),
      ('Serbia', '381', '2-3 digits, no special characters, may be preceded by ''0''', '5-7 digits only, no special characters', '2-3 digits, no special characters, may be preceded by ''0''', '5-7 digits only, no special characters'),
      ('Seychelles', '248', 'area code not used', '6-7 digits only, no special characters', 'area code not used', '6-7 digits only, no special characters'),
      ('Sierra Leone', '232', '2 digits, no special characters', '6 digits only, no special characters', '2 digits, no special characters', '6 digits only, no special characters'),
      ('Singapore', '65', 'area code not used', '8 digits only, no special characters', 'area code not used', '8 digits only, no special characters'),
      ('Sint Maarten', '1', '3 digits, no special characters', '3 digits + optional dash (or dot) + 4 digits', '3 digits, no special characters', '3 digits + optional dash (or dot) + 4 digits'),
      ('Slovakia', '421', '1-3 digits, no special characters, may be preceded by ''0''', '6-8 digits only, no special characters', '1-3 digits, no special characters, may be preceded by ''0''', '6-9 digits only, no special characters'),
      ('Slovenia', '386', '1-2 digits, no special characters, may be preceded by ''0''', '6-7 digits only, no special characters', '2 digits, no special characters, may be preceded by ''0''', '6-7 digits only, no special characters'),
      ('Solomon Islands', '677', 'area code not used', '5 digits only, no special characters', 'area code not used', '7 digits only, no special characters'),
      ('Somalia', '252', 'area code not used', '7-9 digits only, no special characters', 'area code not used', '7-9 digits only, no special characters'),
      ('South Africa', '27', '2 digits, no special characters, may be preceded by ''0''', '7 digits only, no special characters', '2 digits, no special characters, may be preceded by ''0''', '7 digits only, no special characters'),
      ('South Sudan', '211', 'area code not used', '7-10 digits only, no special characters', 'area code not used', '9 digits only, no special characters'),
      ('Spain', '34', '1-3 digits, no special characters', '2-3 digits + optional dash (or space) + 2-3 digits + optional dash (or space) + 2-3 digits + optional dash (or space) + 1-2 digits', '1-3 digits, no special characters', '2-3 digits + optional dash (or space) + 2-3 digits + optional dash (or space) + 2-3 digits + optional dash (or space) + 2 digits'),
      ('Sri Lanka', '94', '2 digits, no special characters, may be preceded by ''0''', '7 digits only, no special characters', '2 digits, no special characters, may be preceded by ''0''', '7 digits only, no special characters'),
      ('Sudan', '249', 'area code not used', '9 digits only, no special characters', 'area code not used', '9 digits only, no special characters'),
      ('Suriname', '597', 'area code not used', '6 digits only, no special characters', 'area code not used', '7 digits only, no special characters'),
      ('Svalbard and Jan Mayen', '47', 'area code not used', '8 digits only, no special characters', 'area code not used', '8 digits only, no special characters'),
      ('Swaziland', '268', 'area code not used', '7-8 digits only, no special characters', 'area code not used', '8 digits only, no special characters'),
      ('Sweden', '46', '1-3 digits, no special characters, may be preceded by ''0''', '5-8 digits only, no special characters', '1-3 digits, no special characters, may be preceded by ''0''', '5-8 digits only, no special characters'),
      ('Switzerland', '41', '2-3 digits, no special characters, may be preceded by ''0''', '7 digits only, no special characters', '2 digits, no special characters, may be preceded by ''0''', '7 digits only, no special characters'),
      ('Syria', '963', '2 digits, no special characters', '6-7 digits only, no special characters', '2 digits, no special characters', '6-7 digits only, no special characters'),
      ('Taiwan', '886', '1-2 digits, no special characters, may be preceded by ''0''', '7-10 digits only, no special characters', '1-2 digits, no special characters, may be preceded by ''0''', '7-9 digits only, no special characters'),
      ('Tajikistan', '992', '3-4 digits, no special characters', '5-6 digits only, no special characters', '3-4 digits, no special characters', '5-6 digits only, no special characters'),
      ('Tanzania', '255', '2 digits, no special characters', '7 digits only, no special characters', '2 digits, no special characters', '7 digits only, no special characters'),
      ('Thailand', '66', '1-3 digits, no special characters', '6-8 digits only, no special characters', '7-8 digits only, no special characters', '7-8 digits only, no special characters'),
      ('Timor-Leste', '670', 'area code not used', '7 digits only, no special characters', 'area code not used', '8 digits only, no special characters'),
      ('Togo', '228', 'area code not used', '7-8 digits only, no special characters', 'area code not used', '8 digits only, no special characters'),
      ('Tokelau', '690', '1 digit', '3 digits', '1 digit', '3 digits'),
      ('Tonga', '676', 'area code not used', '7 digits only, no special characters', 'area code not used', '7 digits only, no special characters'),
      ('Trinidad and Tobago', '1', '3 digits, no special characters', '3 digits + optional dash (or dot) + 4 digits', '3 digits, no special characters', '3 digits + optional dash (or dot) + 4 digits'),
      ('Tunisia', '216', 'area code not used', '8 digits only, no special characters', 'area code not used', '8 digits only, no special characters'),
      ('Turkey', '90', '3 digits, no special characters', '7 digits only, no special characters', '3 digits, no special characters', '7 digits only, no special characters'),
      ('Turkmenistan', '993', '2-3 digits, no special characters', '5-6 digits only, no special characters', '2-3 digits, no special characters', '5-6 digits only, no special characters'),
      ('Turks and Caicos Islands', '1', '3 digits, no special characters', '3 digits + optional dash (or dot) + 4 digits', '3 digits, no special characters', '3 digits + optional dash (or dot) + 4 digits'),
      ('Tuvalu', '688', 'area code not used', '5 digits only, no special characters', 'area code not used', '5 digits only, no special characters'),
      ('U. S. Virgin Islands', '1', '3 digits, no special characters', '3 digits + optional dash (or dot) + 4 digits', '3 digits, no special characters', '3 digits + optional dash (or dot) + 4 digits'),
      ('Uganda', '256', '2-3 digits, no special characters', '6-7 digits only, no special characters', '2-3 digits, no special characters', '6-7 digits only, no special characters'),
      ('Ukraine', '380', '2-4 digits, no special characters', '5-7 digits only, no special characters', '2-4 digits, no special characters', '5-7 digits only, no special characters'),
      ('United Arab Emirates', '971', '1-2 digits, no special characters, may be preceded by ''0''', '7 digits only, no special characters', '2 digits, no special characters, may be preceded by ''0''', '7 digits only, no special characters'),
      ('United Kingdom', '44', '2-5 digits, no special characters, may be preceded by ''0''', '4-8 digits only, no special characters', '2-5 digits, no special characters, may be preceded by ''0''', '5-8 or 10 digits, no special characters, may be preceded by ''0'' if followed by 10 digits'),
      ('United States Minor Outlying Islands', '1', '3 digits, no special characters', '3 digits + optional dash (or dot) + 4 digits', '3 digits, no special characters', '3 digits + optional dash (or dot) + 4 digits'),
      ('United States of America', '1', '3 digits, no special characters', '3 digits + optional dash (or dot) + 4 digits', '3 digits, no special characters', '3 digits + optional dash (or dot) + 4 digits'),
      ('Uruguay', '598', 'area code not used', '8 digits only, no special characters', 'area code not used', '8 digits only, no special characters'),
      ('Uzbekistan', '998', '2 digits, no special characters', '7 digits only, no special characters', '2 digits, no special characters', '7 digits only, no special characters'),
      ('Vanuatu', '678', 'area code not used', '5 digits only, no special characters', 'area code not used', '7 digits only, no special characters'),
      ('Venezuela', '58', '3 digits, no special characters, may be preceded by ''0''', '3 digits + optional dash (or dot) + 4 digits', '3 digits, no special characters, may be preceded by ''0''', '3 digits + optional dash (or dot) + 4 digits'),
      ('Vietnam', '84', '1-3 digits, no special characters', '5-8 digits only, no special characters', '2-3 digits, no special characters', '7-9 digits only, no special characters'),
      ('Wallis and Futuna', '681', 'area code not used', '6 digits only, no special characters', 'area code not used', '6 digits only, no special characters'),
      ('Western Sahara', '212', 'area code not used', '9 digits only, no special characters', 'area code not used', '9 digits only, no special characters'),
      ('Yemen', '967', '1-2 digits, no special characters, may be preceded by ''0''', '6-7 digits only, no special characters', '2 digits, no special characters, may be preceded by ''0''', '6-7 digits only, no special characters'),
      ('Zambia', '260', '3 digits, no special characters', '6 digits only, no special characters', '2-3 digits, no special characters', '6-7 digits only, no special characters'),
      ('Zimbabwe', '263', '1-4 digits, no special characters', '3-8 digits only, no special characters', '2 digits, no special characters', '7 digits only, no special characters')
) AS t(
    country
  , "International Phone Code"
  , "Area Code Validation Message"
  , "Phone Number Validation Message"
  , "Mobile Area Code Message"
  , "Mobile Phone Number Message"
)
;