DROP TABLE IF EXISTS ref_customer_country_code_mapping
;
-- Maps dirty source country codes to canonical country_code
CREATE TABLE ref_customer_country_code_mapping
    AS
SELECT * FROM (VALUES
    ('AE',   'AE'),
    ('AL',   'AL'),
    ('AT',   'AT'),
    ('AU',   'AU'),
    ('BA',   'BA'),
    ('BE',   'BE'),
    ('BG',   'BG'),
    ('BM',   'BM'),
    ('BR',   'BR'),
    ('CA',   'CA'),
    ('CH',   'CH'),
    ('CI',   'CI'),
    ('CL',   'CL'),
    ('CM',   'CM'),
    ('CN',   'CN'),
    ('CR',   'CR'),
    ('DE',   'DE'),
    ('DK',   'DK'),
    ('DZ',   'DZ'),
    ('EC',   'EC'),
    ('EE',   'EE'),
    ('ES',   'ES'),
    ('FI',   'FI'),
    ('FR',   'FR'),
    ('GB',   'GB'),
    ('GR',   'GR'),
    ('HK',   'HK'),
    ('HR',   'HR'),
    ('IE',   'IE'),
    ('IL',   'IL'),
    ('IM',   'IM'),
    ('IS',   'IS'),
    ('IT',   'IT'),
    ('JE',   'JE'),
    ('JP',   'JP'),
    ('KR',   'KR'),
    ('LV',   'LV'),
    ('MA',   'MA'),
    ('MC',   'MC'),
    ('MK',   'MK'),
    ('NG',   'NG'),
    ('NL',   'NL'),
    ('NO',   'NO'),
    ('PT',   'PT'),
    ('PY',   'PY'),
    ('RO',   'RO'),
    ('RS',   'RS'),
    ('SE',   'SE'),
    ('SK',   'SK'),
    ('SN',   'SN'),
    ('TT',   'TT'),
    ('US',   'US'),
    ('ZA',   'ZA')

) AS t(source_country_code, country_code)
;
