DROP TABLE IF EXISTS ref_customer_country_language
;
CREATE TABLE ref_customer_country_language
    AS
SELECT * FROM (VALUES
    ('AE', 'AR'),
    ('AL', 'SQ'),
    ('AT', 'DE'),
    ('AU', 'EN'),
    ('BA', 'BS'),
    ('BE', 'NL'),
    ('BG', 'BG'),
    ('BM', 'EN'),
    ('BR', 'PT'),
    ('CA', 'EN'),
    ('CH', 'DE'),
    ('CI', 'FR'),
    ('CL', 'ES'),
    ('CM', 'FR'),
    ('CN', 'ZH'),
    ('CR', 'ES'),
    ('DE', 'DE'),
    ('DK', 'DA'),
    ('DZ', 'AR'),
    ('EC', 'ES'),
    ('EE', 'ET'),
    ('ES', 'ES'),
    ('FI', 'FI'),
    ('FR', 'FR'),
    ('GB', 'EN'),
    ('GR', 'EL'),
    ('HK', 'ZH'),
    ('HR', 'HR'),
    ('IE', 'EN'),
    ('IL', 'HE'),
    ('IM', 'EN'),
    ('IS', 'IS'),
    ('IT', 'IT'),
    ('JE', 'EN'),
    ('JP', 'JA'),
    ('KR', 'KO'),
    ('LV', 'LV'),
    ('MA', 'AR'),
    ('MC', 'FR'),
    ('MK', 'MK'),
    ('NG', 'EN'),
    ('NL', 'NL'),
    ('NO', 'NO'),
    ('PT', 'PT'),
    ('PY', 'ES'),
    ('RO', 'RO'),
    ('RS', 'SR'),
    ('SE', 'SV'),
    ('SK', 'SK'),
    ('SN', 'FR'),
    ('TT', 'EN'),
    ('US', 'EN'),
    ('ZA', 'EN')
) AS t(country_code, language_code)
;
