DROP TABLE IF EXISTS ref_customer_country_language
;
CREATE TABLE ref_customer_country_language
    AS
SELECT * FROM (VALUES
    ('AE', 'AR', 'AED'),
    ('AL', 'SQ', 'ALL'),
    ('AT', 'DE', 'EUR'),
    ('AU', 'EN', 'AUD'),
    ('BA', 'BS', 'BAM'),
    ('BE', 'NL', 'EUR'),
    ('BG', 'BG', 'BGN'),
    ('BM', 'EN', 'BMD'),
    ('BR', 'PT', 'BRL'),
    ('CA', 'EN', 'CAD'),
    ('CH', 'DE', 'CHF'),
    ('CI', 'FR', 'XOF'),
    ('CL', 'ES', 'CLP'),
    ('CM', 'FR', 'XAF'),
    ('CN', 'ZH', 'CNY'),
    ('CR', 'ES', 'CRC'),
    ('DE', 'DE', 'EUR'),
    ('DK', 'DA', 'DKK'),
    ('DZ', 'AR', 'DZD'),
    ('EC', 'ES', 'USD'),
    ('EE', 'ET', 'EUR'),
    ('ES', 'ES', 'EUR'),
    ('FI', 'FI', 'EUR'),
    ('FR', 'FR', 'EUR'),
    ('GB', 'EN', 'GBP'),
    ('GR', 'EL', 'EUR'),
    ('HK', 'ZH', 'HKD'),
    ('HR', 'HR', 'EUR'),
    ('IE', 'EN', 'EUR'),
    ('IL', 'HE', 'ILS'),
    ('IM', 'EN', 'GBP'),
    ('IS', 'IS', 'ISK'),
    ('IT', 'IT', 'EUR'),
    ('JE', 'EN', 'GBP'),
    ('JP', 'JA', 'JPY'),
    ('KR', 'KO', 'KRW'),
    ('LV', 'LV', 'EUR'),
    ('MA', 'AR', 'MAD'),
    ('MC', 'FR', 'EUR'),
    ('MK', 'MK', 'MKD'),
    ('NG', 'EN', 'NGN'),
    ('NL', 'NL', 'EUR'),
    ('NO', 'NO', 'NOK'),
    ('PT', 'PT', 'EUR'),
    ('PY', 'ES', 'PYG'),
    ('RO', 'RO', 'RON'),
    ('RS', 'SR', 'RSD'),
    ('SE', 'SV', 'SEK'),
    ('SK', 'SK', 'EUR'),
    ('SN', 'FR', 'XOF'),
    ('TT', 'EN', 'TTD'),
    ('US', 'EN', 'USD'),
    ('ZA', 'EN', 'ZAR')
) AS t(country_code, language_code, currency_code)
;
